version: '3.8'

services:
  # Node.js Backend Service
  inc-backend:
    container_name: inc-backend-dev
    build:
      context: .
      dockerfile: Dockerfile.backend.dev
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env
    networks:
      - app-network

  # React Frontend Service (CRA dev server)
  inc-frontend:
    container_name: inc-frontend-dev
    build:
      context: .
      dockerfile: Dockerfile.frontend.dev
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env
    depends_on:
      - inc-backend
    networks:
      - app-network

  # Nginx Proxy Manager (reverse proxy + SSL)
  nginx-proxy-manager:
    image: jc21/nginx-proxy-manager:latest
    container_name: nginx-proxy-manager
    restart: unless-stopped
    ports:
      - "80:80"    # HTTP
      - "81:81"    # Admin UI
      - "443:443"  # HTTPS
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    depends_on:
      - inc-frontend # Ensure frontend is up before proxying
      - inc-backend # Ensure backend is up before proxying
    networks:
      - app-network

networks:
  app-network:
    driver: bridge