# Use a Node.js image
FROM node:18-alpine

# Set the working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package.json package-lock.json ./

# Install all dependencies
RUN npm install

# Expose the port the create-react-app dev server runs on
EXPOSE 3000

# The CMD will be overridden by docker-compose
# This command starts the development server with hot-reloading
CMD ["npm", "run", "react"]