version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: inc_backend
    restart: always
    working_dir: /usr/src/app
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
      - ./nginx/certs:/usr/src/app/nginx/certs:ro
    ports:
      - "5000:80"
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - incnet
    entrypoint: ["/usr/src/app/entrypoint.sh"]
    extra_hosts:
      - "ldap.pmdmc.net:172.18.121.37"   # 🔑 Map external LDAP server

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: inc_frontend
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/certs:/etc/nginx/certs:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - backend
    networks:
      - incnet

  db:
    image: mysql:5.7
    container_name: inc_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: ppi
      MYSQL_USER: portal_dev
      MYSQL_PASSWORD: M@sunur1n
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - db_data:/var/lib/mysql
      - ./db/init:/docker-entrypoint-initdb.d
    networks:
      - incnet

networks:
  incnet:
    driver: bridge

volumes:
  db_data: